title: "Xuan Hoang Duong Nguyen"
description: 
  '
  /swÉ™n/ Hoang Duong /Å‹wiÉ™n/<br>
  Chemistry (BSc) student. This is my personal CV/portfolio.<br>
  <strong>Contact:</strong><br>
  âœ‰ï¸ hoangduong.nguyenx@gmail.com (preferred)<br>
  ğŸ“ +44 754 751 2269<br>
  '

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false
is_project_page: false
