title: "Xuan Hoang Duong Nguyen"
description: 
  "
  /swÉ™n/ Hoang Duong /Å‹wiÉ™n/\n
  Chemistry (BSc) student. This is my personal CV/portfolio.\n
  <strong>Contact:</strong>\n
  âœ‰ï¸ hoangduong.nguyenx@gmail.com (preferred)\n
  ğŸ“ +44 754 751 2269\n
  "

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false
is_project_page: false
